# Generated by Django 4.0.4 on 2022-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
