# Generated by Django 4.0.4 on 2022-06-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='sellHouse.apartment', unique=True),
        ),
    ]
