# Generated by Django 4.0.4 on 2022-06-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0003_alter_transaction_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='sellHouse.apartment'),
        ),
    ]
