# Generated by Django 4.0.4 on 2022-06-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.CharField(choices=[('TK', 'THANH KHE'), ('HC', 'HAI CHAU'), ('LC', 'LIEN CHIEU'), ('ST', 'SON TRA'), ('NHS', 'NGU HANH SON'), ('CL', 'CAM LE'), ('HV', 'HOA VANG'), ('HS', 'HOANG SA')], max_length=20, null=True),
        ),
    ]
