# Generated by Django 4.0.4 on 2022-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0007_apartment_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='district',
            field=models.CharField(choices=[('Thanh Khê', 'Thanh Khê'), ('Hải Châu', 'Hải Châu'), ('Liên Chiểu', 'Liên Chiểu'), ('Sơn Trà', 'Sơn Trà'), ('Ngũ Hành Sơn', 'Ngũ Hành Sơn'), ('Cẩm Lệ', 'Cẩm Lệ'), ('Hòa Vang', 'Hòa Vang'), ('Hoàng Sa', 'Hoàng Sa')], max_length=20),
        ),
    ]
