# Generated by Django 4.0.4 on 2022-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0010_alter_apartment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=5),
        ),
    ]
