# Generated by Django 4.0.4 on 2022-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellHouse', '0011_alter_apartment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=5),
        ),
    ]
